import = [
  "/usr/local/lib/node_modules/alacritty-themes/themes/Nord.toml"
]

[font]
size = 14

  [font.bold]
  family = "JetBrainsMono NF"
  style = "Bold"

  [font.bold_italic]
  family = "JetBrainsMono NF"
  style = "Bold Italic"

  [font.italic]
  family = "JetBrainsMono NF"
  style = "Italic"

  [font.normal]
  family = "JetBrainsMono NF"
  style = "Regular"

[window]
decorations = "Transparent"
opacity = 0.7
blur = true
dynamic_padding = true

[window.padding]
x = 10
y = 30

[cursor]
thickness = 0.2

[cursor.style]
shape = "Beam"
blinking = "Always"

[[keyboard.bindings]]
key = "N"
mods = "Control|Shift"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "ToggleMaximized"

[[keyboard.bindings]]
key = "T"
mods = "Control"
action = "CreateNewTab"
